/**
 * Dev-only refresh tool. Fetches the oEmbed provider registry and writes the
 * vendored snapshot the matcher reads at runtime. Run with:
 *   pnpm --filter api exec tsx scripts/refresh-oembed-providers.ts
 */
import { writeFile } from "node:fs/promises";

interface RawEndpoint {
  url?: string;
  schemes?: string[];
}

interface RawProvider {
  provider_name?: string;
  endpoints?: RawEndpoint[];
}

interface ProviderEntry {
  name: string;
  endpoint: string;
  schemes: string[];
}

const SOURCE = "https://oembed.com/providers.json";
const TARGET = new URL("../src/share/providers.generated.ts", import.meta.url);

const response = await fetch(SOURCE, { headers: { Accept: "application/json" } });
if (!response.ok) throw new Error(`providers.json answered ${response.status}`);

const raw = (await response.json()) as RawProvider[];

// Order is preserved from the source and is the tie-break when two
// providers claim an overlapping scheme: see provider-match.ts.
const entries: ProviderEntry[] = raw.flatMap((provider) =>
  (provider.endpoints ?? []).flatMap((endpoint): ProviderEntry[] => {
    const url = endpoint.url?.replace("{format}", "json");
    const schemes = (endpoint.schemes ?? []).filter((scheme) => scheme.startsWith("https://"));

    if (url === undefined || !url.startsWith("https://") || schemes.length === 0) return [];

    return [{ name: provider.provider_name ?? new URL(url).hostname, endpoint: url, schemes }];
  }),
);

const body = `// Generated by scripts/refresh-oembed-providers.ts. Do not edit by hand.
// Source: ${SOURCE}

export interface ProviderEntry {
  name: string;
  endpoint: string;
  schemes: string[];
}

export const PROVIDERS: readonly ProviderEntry[] = ${JSON.stringify(entries, null, 2)};
`;

await writeFile(TARGET, body, "utf8");
console.log(`wrote ${entries.length} provider endpoints`);
